"""add notification_email_enabled to users

Revision ID: 527c4399ad36
Revises: 510480ed1d75
Create Date: 2026-08-02 21:11:02.032964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '527c4399ad36'
down_revision: Union[str, Sequence[str], None] = '510480ed1d75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('notification_email_enabled', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'notification_email_enabled')
    # ### end Alembic commands ###
